import { UA_ZAPORIZHZHIA_DISTRICT_ENTITIES } from './districts.js';
import { UA_ZAPORIZHZHIA_NEIGHBORHOOD_ENTITIES } from './neighborhoods.js';
import { UA_ZAPORIZHZHIA_POI_ENTITIES } from './poi.js';

export const UA_ZAPORIZHZHIA_ENTITIES = Object.freeze([
  ...UA_ZAPORIZHZHIA_DISTRICT_ENTITIES,
  ...UA_ZAPORIZHZHIA_NEIGHBORHOOD_ENTITIES,
  ...UA_ZAPORIZHZHIA_POI_ENTITIES,
]);
