import { UA_KROPYVNYTSKYI_DISTRICT_ENTITIES } from './districts.js';
import { UA_KROPYVNYTSKYI_NEIGHBORHOOD_ENTITIES } from './neighborhoods.js';
import { UA_KROPYVNYTSKYI_POI_ENTITIES } from './poi.js';
import { UA_KROPYVNYTSKYI_RESIDENTIAL_COMPLEX_ENTITIES } from './residential-complexes.js';

export const UA_KROPYVNYTSKYI_ENTITIES = Object.freeze([
  ...UA_KROPYVNYTSKYI_DISTRICT_ENTITIES,
  ...UA_KROPYVNYTSKYI_NEIGHBORHOOD_ENTITIES,
  ...UA_KROPYVNYTSKYI_POI_ENTITIES,
  ...UA_KROPYVNYTSKYI_RESIDENTIAL_COMPLEX_ENTITIES,
]);
