import { UA_MYKOLAIV_DISTRICT_ENTITIES } from './districts.js';
import { UA_MYKOLAIV_NEIGHBORHOOD_ENTITIES } from './neighborhoods.js';
import { UA_MYKOLAIV_RESIDENTIAL_COMPLEX_ENTITIES } from './residential-complexes.js';
import { UA_MYKOLAIV_STREET_ENTITIES } from './streets.js';
import { UA_MYKOLAIV_REVIEWED_STREET_ENTITIES } from './reviewed-streets.js';
import { UA_MYKOLAIV_POI_ENTITIES } from './poi.js';

export const UA_MYKOLAIV_ENTITIES = Object.freeze([
  ...UA_MYKOLAIV_DISTRICT_ENTITIES,
  ...UA_MYKOLAIV_NEIGHBORHOOD_ENTITIES,
  ...UA_MYKOLAIV_RESIDENTIAL_COMPLEX_ENTITIES,
  ...UA_MYKOLAIV_STREET_ENTITIES,
  ...UA_MYKOLAIV_REVIEWED_STREET_ENTITIES,
  ...UA_MYKOLAIV_POI_ENTITIES,
]);