const osmArea = (idType, type, slug, canonicalName, parentId, lat, lng, osmType, osmId, accuracyM = 700) => Object.freeze({
  id: `uz:tashkent:${idType}:${slug}`,
  type,
  country: 'UZ',
  canonicalName,
  parentId,
  center: Object.freeze({ lat, lng }),
  source: 'osm',
  sourceUrl: `https://www.openstreetmap.org/${osmType}/${osmId}`,
  accuracy: 'neighborhood',
  accuracyM,
  osm: Object.freeze({ type: osmType, id: osmId }),
});

const mappedArea = (idType, type, slug, canonicalName, parentId, lat, lng, sourceUrl, accuracyM = 800) => Object.freeze({
  id: `uz:tashkent:${idType}:${slug}`,
  type,
  country: 'UZ',
  canonicalName,
  parentId,
  center: Object.freeze({ lat, lng }),
  source: 'manual',
  sourceUrl,
  accuracy: 'neighborhood',
  accuracyM,
});

export const TASHKENT_REVIEWED_AREA_ENTITIES = Object.freeze([
  osmArea(
    'local-area',
    'local_area',
    'abu-ali-ibn-sina-2',
    'Abu Ali ibn Sina-2',
    'uz:tashkent:shaykhantahur',
    41.3373461,
    69.1711307,
    'way',
    149989839,
  ),
  osmArea(
    'microdistrict',
    'microdistrict',
    'chilanzar-21',
    'Chilanzar-21',
    'uz:tashkent:uchtepa',
    41.2919358,
    69.1742741,
    'relation',
    1563298,
  ),
  osmArea(
    'microdistrict',
    'microdistrict',
    'chilanzar-22',
    'Chilanzar-22',
    'uz:tashkent:uchtepa',
    41.2882701,
    69.1693758,
    'relation',
    13288750,
  ),
  osmArea(
    'local-area',
    'local_area',
    'guliston',
    'Guliston',
    'uz:tashkent:chilanzar',
    41.2617283,
    69.1591155,
    'relation',
    1856232,
  ),
  mappedArea(
    'microdistrict',
    'microdistrict',
    'dilbulok',
    'Dilbulok',
    'uz:tashkent:yakkasaray',
    41.270339,
    69.24175,
    'https://2gis.uz/tashkent/geo/70030077149953874',
  ),
  mappedArea(
    'mahalla',
    'mahalla',
    'toshkent',
    'Toshkent mahallasi',
    'uz:tashkent:yangihayot',
    41.173696,
    69.204985,
    'https://2gis.uz/tashkent/geo/70030076273161955',
  ),
]);
