export const RO_CITY_ENTITIES = Object.freeze([
  Object.freeze({
    id: 'ro:bucharest',
    type: 'city',
    country: 'RO',
    canonicalName: 'Bucharest',
    center: Object.freeze({ lat: 44.43225, lng: 26.10626 }),
    source: 'geonames',
    sourceUrl: 'https://www.geonames.org/683506/bucharest.html',
    accuracy: 'city',
    accuracyM: 12000,
  }),
  Object.freeze({
    id: 'ro:cluj-napoca',
    type: 'city',
    country: 'RO',
    canonicalName: 'Cluj-Napoca',
    center: Object.freeze({ lat: 46.76667, lng: 23.6 }),
    source: 'geonames',
    sourceUrl: 'https://www.geonames.org/681290/cluj-napoca.html',
    accuracy: 'city',
    accuracyM: 12000,
  }),
  Object.freeze({
    id: 'ro:timisoara',
    type: 'city',
    country: 'RO',
    canonicalName: 'Timișoara',
    center: Object.freeze({ lat: 45.75372, lng: 21.22571 }),
    source: 'geonames',
    sourceUrl: 'https://www.geonames.org/665087/timisoara.html',
    accuracy: 'city',
    accuracyM: 12000,
  }),
  Object.freeze({
    id: 'ro:iasi',
    type: 'city',
    country: 'RO',
    canonicalName: 'Iași',
    center: Object.freeze({ lat: 47.16667, lng: 27.6 }),
    source: 'geonames',
    sourceUrl: 'https://www.geonames.org/675810/iasi.html',
    accuracy: 'city',
    accuracyM: 12000,
  }),
  Object.freeze({
    id: 'ro:constanta',
    type: 'city',
    country: 'RO',
    canonicalName: 'Constanța',
    center: Object.freeze({ lat: 44.18073, lng: 28.63432 }),
    source: 'geonames',
    sourceUrl: 'https://www.geonames.org/680963/constanta.html',
    accuracy: 'city',
    accuracyM: 12000,
  }),
  Object.freeze({
    id: 'ro:brasov',
    type: 'city',
    country: 'RO',
    canonicalName: 'Brașov',
    center: Object.freeze({ lat: 45.64861, lng: 25.60613 }),
    source: 'geonames',
    sourceUrl: 'https://www.geonames.org/683844/brasov.html',
    accuracy: 'city',
    accuracyM: 12000,
  }),
]);
